services:
  postgres:
    image: postgres:16
    container_name: media-db
    environment:
      POSTGRES_USER: ${DB_USER:-media_user}
      POSTGRES_PASSWORD: ${DB_PASS:-media_pass}
      POSTGRES_DB: ${DB_NAME:-media_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "5432:5432"
    networks:
      - media-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: media-redis
    deploy:
      resources:
        limits:
          memory: 128M
    ports:
      - "6379:6379"
    networks:
      - media-network
    restart: unless-stopped

  kafka:
    image: apache/kafka:3.7.0
    container_name: media-kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      # INTERNAL: docker network içindeki servisler (app container)
      # EXTERNAL: host makineden IDE ile çalıştırma için
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_HEAP_OPTS: "-Xmx256m -Xms128m"
    volumes:
      - kafka_data:/var/lib/kafka/data
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "9092:9092"   # Docker internal (app container)
      - "29092:29092" # Host access (IDE / local geliştirme)
    networks:
      - media-network
    restart: unless-stopped

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: media-backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_TOOL_OPTIONS=-Xmx512m -Xms256m
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME:-media_db}
      - SPRING_DATASOURCE_USERNAME=${DB_USER:-media_user}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS:-media_pass}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - TMDB_API_KEY=${TMDB_API_KEY}
      - AES_SECRET_KEY=${AES_SECRET_KEY}
    depends_on:
      - postgres
      - redis
      - kafka
    deploy:
      resources:
        limits:
          memory: 768M
    ports:
      - "8080:8080"
    networks:
      - media-network
    restart: unless-stopped

volumes:
  postgres_data:
  kafka_data:

networks:
  media-network:
    driver: bridge
